
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('testResults').del()
    .then(function () {
      // Inserts seed entries
      return knex('testResults').insert([
        {
          patient_id: 1,
          date: "07/24/2017",
          glucose: 74,
          creatinine: 27,
          sodium: 65,
          potassium: 49,
          chloride: 40,
          carbon_dioxide: 88,
          calcium: 17,
          protein: 40,
          cholesterol: 18,
          triglycerides:65
        },
        {
          patient_id: 1,
          date: "10/26/2017",
          glucose: 76,
          creatinine: 32,
          sodium: 68,
          potassium: 22,
          chloride: 47,
          carbon_dioxide: 82,
          calcium: 20,
          protein: 60,
          cholesterol: 10,
          triglycerides:61
        },
        {
          patient_id: 1,
          date: "1/25/2018",
          glucose: 73,
          creatinine: 36,
          sodium: 66,
          potassium: 16,
          chloride: 56,
          carbon_dioxide: 84,
          calcium: 25,
          protein: 50,
          cholesterol: 14,
          triglycerides:67
        },
        {
          patient_id: 1,
          date: "04/24/2018",
          glucose: 70,
          creatinine: 30,
          sodium: 90,
          potassium: 10,
          chloride: 64,
          carbon_dioxide: 80,
          calcium: 31,
          protein: 48,
          cholesterol: 22,
          triglycerides:65
        },
        {
          patient_id: 2,
          date: "07/24/2017",
          glucose: 74,
          creatinine: 27,
          sodium: 65,
          potassium: 49,
          chloride: 40,
          carbon_dioxide: 88,
          calcium: 17,
          protein: 40,
          cholesterol: 18,
          triglycerides:65
        },
        {
          patient_id: 2,
          date: "10/26/2017",
          glucose: 76,
          creatinine: 32,
          sodium: 68,
          potassium: 22,
          chloride: 47,
          carbon_dioxide: 82,
          calcium: 20,
          protein: 60,
          cholesterol: 10,
          triglycerides:61
        },
        {
          patient_id: 2,
          date: "1/25/2018",
          glucose: 73,
          creatinine: 36,
          sodium: 66,
          potassium: 16,
          chloride: 56,
          carbon_dioxide: 84,
          calcium: 25,
          protein: 50,
          cholesterol: 14,
          triglycerides:67
        },
        {
          patient_id: 2,
          date: "04/24/2018",
          glucose: 70,
          creatinine: 30,
          sodium: 90,
          potassium: 10,
          chloride: 64,
          carbon_dioxide: 80,
          calcium: 31,
          protein: 48,
          cholesterol: 22,
          triglycerides:65
        },
        {
          patient_id: 3,
          date: "07/24/2017",
          glucose: 74,
          creatinine: 27,
          sodium: 65,
          potassium: 49,
          chloride: 40,
          carbon_dioxide: 88,
          calcium: 17,
          protein: 40,
          cholesterol: 18,
          triglycerides:65
        },
        {
          patient_id: 3,
          date: "10/26/2017",
          glucose: 76,
          creatinine: 32,
          sodium: 68,
          potassium: 22,
          chloride: 47,
          carbon_dioxide: 82,
          calcium: 20,
          protein: 60,
          cholesterol: 10,
          triglycerides:61
        },
        {
          patient_id: 3,
          date: "1/25/2018",
          glucose: 73,
          creatinine: 36,
          sodium: 66,
          potassium: 16,
          chloride: 56,
          carbon_dioxide: 84,
          calcium: 25,
          protein: 50,
          cholesterol: 14,
          triglycerides:67
        },
        {
          patient_id: 3,
          date: "04/24/2018",
          glucose: 70,
          creatinine: 30,
          sodium: 90,
          potassium: 10,
          chloride: 64,
          carbon_dioxide: 80,
          calcium: 31,
          protein: 48,
          cholesterol: 22,
          triglycerides:65
        },
        {
          patient_id: 4,
          date: "07/24/2017",
          glucose: 74,
          creatinine: 27,
          sodium: 65,
          potassium: 49,
          chloride: 40,
          carbon_dioxide: 88,
          calcium: 17,
          protein: 40,
          cholesterol: 18,
          triglycerides:65
        },
        {
          patient_id: 4,
          date: "10/26/2017",
          glucose: 76,
          creatinine: 32,
          sodium: 68,
          potassium: 22,
          chloride: 47,
          carbon_dioxide: 82,
          calcium: 20,
          protein: 60,
          cholesterol: 10,
          triglycerides:61
        },
        {
          patient_id: 4,
          date: "1/25/2018",
          glucose: 73,
          creatinine: 36,
          sodium: 66,
          potassium: 16,
          chloride: 56,
          carbon_dioxide: 84,
          calcium: 25,
          protein: 50,
          cholesterol: 14,
          triglycerides:67
        },
        {
          patient_id: 4,
          date: "04/24/2018",
          glucose: 70,
          creatinine: 30,
          sodium: 90,
          potassium: 10,
          chloride: 64,
          carbon_dioxide: 80,
          calcium: 31,
          protein: 48,
          cholesterol: 22,
          triglycerides:65
        },
        {
          patient_id: 5,
          date: "07/24/2017",
          glucose: 74,
          creatinine: 27,
          sodium: 65,
          potassium: 49,
          chloride: 40,
          carbon_dioxide: 88,
          calcium: 17,
          protein: 40,
          cholesterol: 18,
          triglycerides:65
        },
        {
          patient_id: 5,
          date: "10/26/2017",
          glucose: 76,
          creatinine: 32,
          sodium: 68,
          potassium: 22,
          chloride: 47,
          carbon_dioxide: 82,
          calcium: 20,
          protein: 60,
          cholesterol: 10,
          triglycerides:61
        },
        {
          patient_id: 5,
          date: "1/25/2018",
          glucose: 73,
          creatinine: 36,
          sodium: 66,
          potassium: 16,
          chloride: 56,
          carbon_dioxide: 84,
          calcium: 25,
          protein: 50,
          cholesterol: 14,
          triglycerides:67
        },
        {
          patient_id: 5,
          date: "04/24/2018",
          glucose: 70,
          creatinine: 30,
          sodium: 90,
          potassium: 10,
          chloride: 64,
          carbon_dioxide: 80,
          calcium: 31,
          protein: 48,
          cholesterol: 22,
          triglycerides:65
        }
      ]);
    });
};
